/**
 * Copyright (c) 2026 Ankur Sinha. All rights reserved.
 * Licensed under the terms in /LICENSE — proprietary, not OSI-approved.
 * https://github.com/sinhaankur/Portfolio/blob/main/LICENSE
 */

import type React from "react"
import type { Metadata, Viewport } from "next"
import { Inter, Instrument_Serif, JetBrains_Mono, Fraunces } from "next/font/google"
import { ThemeProvider } from "@/components/theme-provider"
import { DisplayPrefsProvider } from "@/components/display-prefs"
import "./globals.css"

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
})

// Editorial display font with real optical character at large sizes.
// Used on case-study headlines and section h2s — anywhere Inter Light
// was feeling generic at display size.
const fraunces = Fraunces({
  subsets: ["latin"],
  variable: "--font-fraunces",
  // Variable axes — keeps the file count down while giving us weight + opsz.
  axes: ["opsz", "SOFT", "WONK"],
  style: ["normal", "italic"],
  display: "swap",
})

// Instrument Serif still appears for short inline italic moments
// (single-word emphasis like "collaborate"). Fraunces handles the big stuff.
const instrument = Instrument_Serif({
  subsets: ["latin"],
  weight: "400",
  style: ["normal", "italic"],
  variable: "--font-instrument",
  display: "swap",
})

const jetbrains = JetBrains_Mono({
  subsets: ["latin"],
  variable: "--font-jetbrains",
  display: "swap",
})

const SITE_URL = "https://www.sinhaankur.com"
const SITE_NAME = "Ankur Sinha"
const SITE_TAGLINE = "Principal UX Designer · Human–AI Interaction"
const SITE_DESCRIPTION =
  "Principal UX Designer working on human-in-the-loop interfaces for agentic AI. Helm, Sentinel, Recourse — code prototypes for keeping humans in command."

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: {
    default: `${SITE_NAME} · ${SITE_TAGLINE}`,
    template: `%s · ${SITE_NAME}`,
  },
  description: SITE_DESCRIPTION,
  authors: [{ name: SITE_NAME, url: SITE_URL }],
  creator: SITE_NAME,
  applicationName: SITE_NAME,
  keywords: [
    "UX Designer",
    "Principal Designer",
    "Human–AI Interaction",
    "Agentic AI",
    "Design Engineer",
    "Portfolio",
    "Ankur Sinha",
  ],
  alternates: {
    canonical: SITE_URL,
  },
  openGraph: {
    type: "website",
    url: SITE_URL,
    siteName: SITE_NAME,
    title: `${SITE_NAME} · ${SITE_TAGLINE}`,
    description: SITE_DESCRIPTION,
    locale: "en_US",
    // Canonical 1200×630 generated by app/opengraph-image.tsx at build time.
    // Falls back to /og-image.svg for clients that don't fetch the generated PNG.
    images: [
      {
        url: "/opengraph-image",
        width: 1200,
        height: 630,
        alt: `${SITE_NAME} — ${SITE_TAGLINE}`,
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: `${SITE_NAME} · ${SITE_TAGLINE}`,
    description: SITE_DESCRIPTION,
    images: ["/opengraph-image"],
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-image-preview": "large",
      "max-snippet": -1,
      "max-video-preview": -1,
    },
  },
  formatDetection: {
    telephone: false,
    email: false,
    address: false,
  },
}

export const viewport: Viewport = {
  themeColor: [
    { media: "(prefers-color-scheme: dark)", color: "#050505" },
    { media: "(prefers-color-scheme: light)", color: "#f5f5f0" },
  ],
  width: "device-width",
  initialScale: 1,
  // Allow zoom — pinch-to-zoom on phones is an accessibility floor we don't disable.
  maximumScale: 5,
}

// JSON-LD Person schema for Google's knowledge panel + LinkedIn previews.
const personSchema = {
  "@context": "https://schema.org",
  "@type": "Person",
  name: "Ankur Sinha",
  url: SITE_URL,
  jobTitle: "Principal UX Designer",
  description: SITE_DESCRIPTION,
  knowsAbout: [
    "Human–AI Interaction",
    "Agentic AI",
    "UX Design",
    "Design Engineering",
    "Prototyping",
    "Distributed Systems",
  ],
  sameAs: [
    "https://github.com/unhosted-ai",
    "https://www.linkedin.com/in/sinhaankur/",
  ],
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${inter.variable} ${fraunces.variable} ${instrument.variable} ${jetbrains.variable}`}
    >
      <body className="font-sans antialiased overflow-x-hidden bg-background text-foreground">
        {/* JSON-LD Person schema — feeds Google knowledge panel + rich previews. */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(personSchema) }}
        />
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem={false}
          disableTransitionOnChange={false}
        >
          <DisplayPrefsProvider>
            <a href="#main" className="skip-link">
              Skip to main content
            </a>
            <div className="noise-overlay" aria-hidden="true" />
            {children}
          </DisplayPrefsProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
