/**
 * Copyright (c) 2026 Ankur Sinha. All rights reserved.
 * Licensed under the terms in /LICENSE — proprietary, not OSI-approved.
 * https://github.com/sinhaankur/portfolio-2026/blob/main/LICENSE
 */

import type React from "react"
import type { Metadata, Viewport } from "next"
import Script from "next/script"
import { Inter, Instrument_Serif, JetBrains_Mono, Fraunces, Noto_Sans_Arabic, Noto_Sans_JP } from "next/font/google"
import { ThemeProvider } from "@/components/theme-provider"
import { TimeOfDayTheme } from "@/components/time-of-day-theme"
import { DisplayPrefsProvider } from "@/components/display-prefs"
import { VisitorAnalytics } from "@/components/analytics/visitor-analytics"
import { Preloader } from "@/components/preloader"
import "./globals.css"

// Google Tag Manager container — feeds GA4 + any future marketing tags from
// one place so we don't have to touch the codebase for every analytics change.
// Tags themselves (GA4 config, custom events) are configured in the GTM UI.
const GTM_ID = "GTM-N6T2NFT3"

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
})

// Editorial display font with real optical character at large sizes.
// Used on case-study headlines and section h2s — anywhere Inter Light
// was feeling generic at display size.
const fraunces = Fraunces({
  subsets: ["latin"],
  variable: "--font-fraunces",
  // Variable axes — keeps the file count down while giving us weight + opsz.
  axes: ["opsz", "SOFT", "WONK"],
  style: ["normal", "italic"],
  display: "swap",
})

// Instrument Serif still appears for short inline italic moments
// (single-word emphasis like "collaborate"). Fraunces handles the big stuff.
const instrument = Instrument_Serif({
  subsets: ["latin"],
  weight: "400",
  style: ["normal", "italic"],
  variable: "--font-instrument",
  display: "swap",
})

const jetbrains = JetBrains_Mono({
  subsets: ["latin"],
  variable: "--font-jetbrains",
  display: "swap",
})

// Arabic + Japanese faces for the localized /ar and /ja shells. Loaded globally
// (so the switcher works from any page) but only applied via [lang="ar"|"ja"] in
// globals.css, so English pages keep the Latin type system unchanged.
const notoArabic = Noto_Sans_Arabic({
  subsets: ["arabic"],
  variable: "--font-ar",
  display: "swap",
})
const notoJP = Noto_Sans_JP({
  subsets: ["latin"], // JP glyphs ship regardless; "latin" keeps the requested subset valid
  variable: "--font-jp",
  display: "swap",
})

const SITE_URL = "https://www.sinhaankur.com"
const SITE_NAME = "Ankur Sinha"
const SITE_TAGLINE = "Design × Engineering × AI"
const SITE_DESCRIPTION =
  "UX designer by craft, exploring AI by building it. Years of product design (Oracle, Deloitte, and more) plus a lab of human-in-the-loop AI experiments shipped as working code."

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: {
    default: `${SITE_NAME} · ${SITE_TAGLINE}`,
    template: `%s · ${SITE_NAME}`,
  },
  description: SITE_DESCRIPTION,
  authors: [{ name: SITE_NAME, url: SITE_URL }],
  creator: SITE_NAME,
  applicationName: SITE_NAME,
  keywords: [
    "UX Designer",
    "Product Designer",
    "Design Engineer",
    "Human–AI Interaction",
    "Agentic AI",
    "AI prototyping",
    "Portfolio",
    "Ankur Sinha",
  ],
  alternates: {
    // Homepage self-canonical (trailing slash to match `trailingSlash: true`).
    // Sub-pages MUST override this with their own route via `canonicalMetadata()`
    // (see lib/seo.ts) — otherwise they inherit the homepage canonical and Google
    // de-duplicates every page into "/", refusing to index them.
    canonical: "/",
  },
  openGraph: {
    type: "website",
    url: SITE_URL,
    siteName: SITE_NAME,
    title: `${SITE_NAME} · ${SITE_TAGLINE}`,
    description: SITE_DESCRIPTION,
    locale: "en_US",
    // Canonical 1200×630 generated by app/opengraph-image.tsx at build time.
    // Falls back to /og-image.svg for clients that don't fetch the generated PNG.
    images: [
      {
        url: "/opengraph-image",
        width: 1200,
        height: 630,
        alt: `${SITE_NAME} — ${SITE_TAGLINE}`,
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: `${SITE_NAME} · ${SITE_TAGLINE}`,
    description: SITE_DESCRIPTION,
    images: ["/opengraph-image"],
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-image-preview": "large",
      "max-snippet": -1,
      "max-video-preview": -1,
    },
  },
  formatDetection: {
    telephone: false,
    email: false,
    address: false,
  },
  manifest: "/manifest.webmanifest",
  icons: {
    apple: "/apple-touch-icon.png",
    icon: "/icon.svg",
  },
  appleWebApp: {
    capable: true,
    title: SITE_NAME,
    statusBarStyle: "black-translucent",
  },
}

export const viewport: Viewport = {
  themeColor: [
    { media: "(prefers-color-scheme: dark)", color: "#050505" },
    { media: "(prefers-color-scheme: light)", color: "#f5f5f0" },
  ],
  width: "device-width",
  initialScale: 1,
  // Allow zoom — pinch-to-zoom on phones is an accessibility floor we don't disable.
  maximumScale: 5,
}

// JSON-LD Person schema for Google's knowledge panel + LinkedIn previews.
// sameAs is the entity-resolution signal: it tells search engines these profiles
// are the same person, so searching "Ankur Sinha" can consolidate into one entity.
const personSchema = {
  "@context": "https://schema.org",
  "@type": "Person",
  name: "Ankur Sinha",
  url: SITE_URL,
  image: `${SITE_URL}/opengraph-image`,
  jobTitle: "UX Designer",
  description: SITE_DESCRIPTION,
  address: {
    "@type": "PostalAddress",
    addressLocality: "Toronto",
    addressRegion: "ON",
    addressCountry: "CA",
  },
  knowsAbout: [
    "UX Design",
    "Product Design",
    "Human–AI Interaction",
    "Agentic AI",
    "Design Engineering",
    "Prototyping",
    "Distributed Systems",
  ],
  sameAs: [
    "https://www.linkedin.com/in/sinhaankur27",
    "https://github.com/sinhaankur",
    "https://github.com/unhosted-ai",
  ],
}

// WebSite schema — names the site as a distinct entity (separate from the Person)
// and declares its publisher, so search engines can consolidate the domain and
// are eligible to render sitelinks under the main result.
const websiteSchema = {
  "@context": "https://schema.org",
  "@type": "WebSite",
  name: SITE_NAME,
  alternateName: `${SITE_NAME} · ${SITE_TAGLINE}`,
  url: SITE_URL,
  description: SITE_DESCRIPTION,
  inLanguage: "en",
  author: { "@type": "Person", name: SITE_NAME, url: SITE_URL },
  publisher: { "@type": "Person", name: SITE_NAME, url: SITE_URL },
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${inter.variable} ${fraunces.variable} ${instrument.variable} ${jetbrains.variable} ${notoArabic.variable} ${notoJP.variable}`}
    >
      <head>
        {/* SoundCloud music now loads ONLY after the user clicks play (deferred),
            so we no longer hold open full preconnects on every page. A light
            dns-prefetch still shaves the eventual click latency without warming
            a TLS connection most visitors never use. */}
        <link rel="dns-prefetch" href="https://w.soundcloud.com" />
        {/* Preconnect to GTM so the container fetch isn't gated on a fresh
            DNS + TLS handshake. */}
        <link rel="preconnect" href="https://www.googletagmanager.com" />
        {/* GTM container init — loads the container script async via
            next/script so it doesn't block first paint. Tags fire client-side
            from inside the GTM dashboard once configured (GA4, etc.). */}
        <Script id="gtm-init" strategy="afterInteractive">
          {`(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','${GTM_ID}');`}
        </Script>
        <Script id="pwa-sw-register" strategy="afterInteractive">
          {`if ('serviceWorker' in navigator) {
  window.addEventListener('load', () => {
    navigator.serviceWorker.register('/sw.js').catch(() => {});
  });
}`}
        </Script>
        <Script id="person-schema" type="application/ld+json" strategy="beforeInteractive">
          {JSON.stringify(personSchema)}
        </Script>
        <Script id="website-schema" type="application/ld+json" strategy="beforeInteractive">
          {JSON.stringify(websiteSchema)}
        </Script>
      </head>
      <body className="font-sans antialiased overflow-x-hidden bg-background text-foreground">
        <VisitorAnalytics />
        {/* GTM noscript fallback — fires the container for visitors with
            JS disabled so basic page-view counts still land. */}
        <noscript>
          <iframe
            src={`https://www.googletagmanager.com/ns.html?id=${GTM_ID}`}
            height="0"
            width="0"
            style={{ display: "none", visibility: "hidden" }}
            title="Google Tag Manager"
          />
        </noscript>
        {/* No-JS fallback — the site is a heavy R3F/SPA experience, so without
            JS the viewport would otherwise be blank. This gives crawlers,
            text browsers, and JS-disabled visitors a real page: name, role,
            short bio, and direct links to the case studies + contact. */}
        <noscript>
          <div className="fixed inset-0 z-50 overflow-auto bg-background text-foreground px-6 py-16 md:py-24">
            <div className="max-w-2xl mx-auto">
              <p className="font-mono text-[11px] tracking-[0.3em] uppercase text-foreground/55 mb-3">
                Ankur Sinha
              </p>
              <h1 className="font-serif text-3xl md:text-5xl leading-tight mb-6">
                Design × Engineering × AI
              </h1>
              <p className="text-base md:text-lg leading-relaxed text-foreground/85 mb-8">
                Engineer-turned-designer in Toronto. Currently Principal UX at
                Oracle on OCI Database Tools, and building Unhosted — frontier
                AI inference on hardware you own — on evenings and weekends.
              </p>
              <p className="text-sm leading-relaxed text-foreground/70 mb-8">
                This site is an interactive 3D portfolio (R3F + Next.js).
                You're seeing the JavaScript-disabled fallback. Enable
                JavaScript to load the universe engine and the live case
                studies, or use the direct links below.
              </p>
              <ul className="space-y-3 font-mono text-xs tracking-[0.18em] uppercase text-foreground/85">
                <li>
                  <a className="underline underline-offset-4" href="/works/oracle">Oracle · Database Tools</a>
                </li>
                <li>
                  <a className="underline underline-offset-4" href="/works/deloitte">Deloitte</a>
                </li>
                <li>
                  <a className="underline underline-offset-4" href="/works/snowtint">Snowtint</a>
                </li>
                <li>
                  <a className="underline underline-offset-4" href="/works/rage">RAGE</a>
                </li>
                <li>
                  <a className="underline underline-offset-4" href="/lab/unhosted">Unhosted</a>
                </li>
                <li>
                  <a className="underline underline-offset-4" href="/lab/usability-engine">Usability Engine</a>
                </li>
                <li>
                  <a className="underline underline-offset-4" href="/usability">Usability guide</a>
                </li>
                <li>
                  <a className="underline underline-offset-4" href="/skills">Skills matrix</a>
                </li>
                <li>
                  <a className="underline underline-offset-4" href="/ankur-sinha-resume.pdf">Résumé (PDF)</a>
                </li>
                <li>
                  <a className="underline underline-offset-4" href="mailto:h99311@gmail.com">Contact · h99311@gmail.com</a>
                </li>
                <li>
                  <a className="underline underline-offset-4" href="https://github.com/sinhaankur" rel="noopener">GitHub</a>
                </li>
              </ul>
            </div>
          </div>
        </noscript>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem={false}
          disableTransitionOnChange={false}
        >
          <DisplayPrefsProvider>
            <TimeOfDayTheme />
            <Preloader />
            <a href="#main" className="skip-link">
              Skip to main content
            </a>
            <div className="noise-overlay" aria-hidden="true" />
            {children}
          </DisplayPrefsProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
