/**
 * dna-annotations.ts — AUTO-GENERATED by scripts/fetch-dna-annotations.mjs.
 * Do not edit by hand; re-run the script to refresh.
 *
 * Validated, cited per-variant annotations pulled from open genomics APIs
 * (MyVariant.info, aggregating dbSNP · ClinVar · gnomAD · CADD · snpEff). Each
 * record carries source URLs as proof. Population frequencies are "how common
 * in a reference cohort", NOT an ancestry claim about you.
 *
 * Generated: 2026-07-25
 */

export type DnaAnnotation = {
  rsid: string
  gene: string | null
  geneName: string | null
  vartype: string | null
  chrom: string | null
  consequence: string | null
  proteinChange: string | null
  impact: { sift: string | null; polyphen: string | null } | null
  clinvar: { significance: string; condition: string }[]
  freqs: { cohort: string; allele: string; freq: number }[]
  sources: { dbsnp: string; clinvar: string; gnomad: string; ensembl: string; myvariant: string }
  missing?: boolean
  error?: string
}

export const DNA_ANNOTATIONS: Record<string, DnaAnnotation> = {
  "rs4988235": {
    "rsid": "rs4988235",
    "gene": "MCM6",
    "geneName": "minichromosome maintenance complex component 6",
    "vartype": "snv",
    "chrom": "2",
    "impact": null,
    "consequence": "INTRONIC",
    "proteinChange": null,
    "clinvar": [
      {
        "significance": "association",
        "condition": "LACTASE PERSISTENCE"
      }
    ],
    "freqs": [
      {
        "cohort": "1000 Genomes (global)",
        "allele": "A",
        "freq": 0.168
      },
      {
        "cohort": "gnomAD (global)",
        "allele": "A",
        "freq": 0.41
      },
      {
        "cohort": "TOPMed (US)",
        "allele": "A",
        "freq": 0.359
      }
    ],
    "sources": {
      "dbsnp": "https://www.ncbi.nlm.nih.gov/snp/rs4988235",
      "clinvar": "https://www.ncbi.nlm.nih.gov/clinvar/?term=rs4988235",
      "gnomad": "https://gnomad.broadinstitute.org/variant/rs4988235?dataset=gnomad_r4",
      "ensembl": "https://www.ensembl.org/Homo_sapiens/Variation/Explore?v=rs4988235",
      "myvariant": "https://myvariant.info/v1/query?q=dbsnp.rsid:rs4988235"
    }
  },
  "rs762551": {
    "rsid": "rs762551",
    "gene": "CYP1A2",
    "geneName": "cytochrome P450 family 1 subfamily A member 2",
    "vartype": "snv",
    "chrom": "15",
    "impact": null,
    "consequence": "MODIFIER impact",
    "proteinChange": null,
    "clinvar": [],
    "freqs": [
      {
        "cohort": "1000 Genomes (global)",
        "allele": "C",
        "freq": 0.366
      },
      {
        "cohort": "gnomAD (global)",
        "allele": "C",
        "freq": 0.325
      },
      {
        "cohort": "TOPMed (US)",
        "allele": "C",
        "freq": 0.324
      },
      {
        "cohort": "Korean",
        "allele": "C",
        "freq": 0.354
      },
      {
        "cohort": "Japanese (ToMMo)",
        "allele": "C",
        "freq": 0.364
      },
      {
        "cohort": "Vietnamese",
        "allele": "C",
        "freq": 0.286
      },
      {
        "cohort": "UK (ALSPAC)",
        "allele": "C",
        "freq": 0.276
      }
    ],
    "sources": {
      "dbsnp": "https://www.ncbi.nlm.nih.gov/snp/rs762551",
      "clinvar": "https://www.ncbi.nlm.nih.gov/clinvar/?term=rs762551",
      "gnomad": "https://gnomad.broadinstitute.org/variant/rs762551?dataset=gnomad_r4",
      "ensembl": "https://www.ensembl.org/Homo_sapiens/Variation/Explore?v=rs762551",
      "myvariant": "https://myvariant.info/v1/query?q=dbsnp.rsid:rs762551"
    }
  },
  "rs671": {
    "rsid": "rs671",
    "gene": "ALDH2",
    "geneName": "aldehyde dehydrogenase 2 family member",
    "vartype": "snv",
    "chrom": "12",
    "impact": {
      "sift": "deleterious",
      "polyphen": "probably damaging"
    },
    "consequence": "NON_SYNONYMOUS",
    "proteinChange": "p.Glu504Lys",
    "clinvar": [
      {
        "significance": "risk factor",
        "condition": "ESOPHAGEAL CANCER, ALCOHOL-RELATED, SUSCEPTIBILITY TO"
      },
      {
        "significance": "risk factor",
        "condition": "SUBLINGUAL NITROGLYCERIN, SUSCEPTIBILITY TO POOR RESPONSE TO"
      },
      {
        "significance": "risk factor",
        "condition": "Susceptibility to hangover"
      },
      {
        "significance": "protective",
        "condition": "Alcohol dependence"
      },
      {
        "significance": "drug response",
        "condition": "Alcohol sensitivity, acute"
      },
      {
        "significance": "Pathogenic",
        "condition": "AMED syndrome, digenic"
      }
    ],
    "freqs": [
      {
        "cohort": "1000 Genomes (global)",
        "allele": "A",
        "freq": 0.034
      },
      {
        "cohort": "gnomAD (global)",
        "allele": "A",
        "freq": 0.006
      },
      {
        "cohort": "TOPMed (US)",
        "allele": "A",
        "freq": 0.009
      },
      {
        "cohort": "Korean",
        "allele": "A",
        "freq": 0.173
      },
      {
        "cohort": "Japanese (ToMMo)",
        "allele": "A",
        "freq": 0.194
      },
      {
        "cohort": "Vietnamese",
        "allele": "A",
        "freq": 0.209
      },
      {
        "cohort": "UK (ALSPAC)",
        "allele": "A",
        "freq": 0.001
      }
    ],
    "sources": {
      "dbsnp": "https://www.ncbi.nlm.nih.gov/snp/rs671",
      "clinvar": "https://www.ncbi.nlm.nih.gov/clinvar/?term=rs671",
      "gnomad": "https://gnomad.broadinstitute.org/variant/rs671?dataset=gnomad_r4",
      "ensembl": "https://www.ensembl.org/Homo_sapiens/Variation/Explore?v=rs671",
      "myvariant": "https://myvariant.info/v1/query?q=dbsnp.rsid:rs671"
    }
  },
  "rs1229984": {
    "rsid": "rs1229984",
    "gene": "ADH1B",
    "geneName": "alcohol dehydrogenase 1B (class I), beta polypeptide",
    "vartype": "snv",
    "chrom": "4",
    "impact": {
      "sift": "tolerated",
      "polyphen": null
    },
    "consequence": "NON_SYNONYMOUS",
    "proteinChange": "p.His48Pro",
    "clinvar": [],
    "freqs": [
      {
        "cohort": "1000 Genomes (global)",
        "allele": "T",
        "freq": 0.146
      },
      {
        "cohort": "TOPMed (US)",
        "allele": "T",
        "freq": 0.069
      },
      {
        "cohort": "Korean",
        "allele": "T",
        "freq": 0.759
      },
      {
        "cohort": "Japanese (ToMMo)",
        "allele": "T",
        "freq": 0.754
      },
      {
        "cohort": "Vietnamese",
        "allele": "T",
        "freq": 0.69
      },
      {
        "cohort": "UK (ALSPAC)",
        "allele": "T",
        "freq": 0.031
      }
    ],
    "sources": {
      "dbsnp": "https://www.ncbi.nlm.nih.gov/snp/rs1229984",
      "clinvar": "https://www.ncbi.nlm.nih.gov/clinvar/?term=rs1229984",
      "gnomad": "https://gnomad.broadinstitute.org/variant/rs1229984?dataset=gnomad_r4",
      "ensembl": "https://www.ensembl.org/Homo_sapiens/Variation/Explore?v=rs1229984",
      "myvariant": "https://myvariant.info/v1/query?q=dbsnp.rsid:rs1229984"
    }
  },
  "rs9939609": {
    "rsid": "rs9939609",
    "gene": "FTO",
    "geneName": "FTO alpha-ketoglutarate dependent dioxygenase",
    "vartype": "snv",
    "chrom": "16",
    "impact": null,
    "consequence": "INTRONIC",
    "proteinChange": null,
    "clinvar": [],
    "freqs": [
      {
        "cohort": "1000 Genomes (global)",
        "allele": "A",
        "freq": 0.344
      },
      {
        "cohort": "gnomAD (global)",
        "allele": "A",
        "freq": 0.416
      },
      {
        "cohort": "TOPMed (US)",
        "allele": "A",
        "freq": 0.401
      },
      {
        "cohort": "Korean",
        "allele": "A",
        "freq": 0.131
      },
      {
        "cohort": "Japanese (ToMMo)",
        "allele": "A",
        "freq": 0.2
      },
      {
        "cohort": "Vietnamese",
        "allele": "A",
        "freq": 0.148
      },
      {
        "cohort": "UK (ALSPAC)",
        "allele": "A",
        "freq": 0.389
      }
    ],
    "sources": {
      "dbsnp": "https://www.ncbi.nlm.nih.gov/snp/rs9939609",
      "clinvar": "https://www.ncbi.nlm.nih.gov/clinvar/?term=rs9939609",
      "gnomad": "https://gnomad.broadinstitute.org/variant/rs9939609?dataset=gnomad_r4",
      "ensembl": "https://www.ensembl.org/Homo_sapiens/Variation/Explore?v=rs9939609",
      "myvariant": "https://myvariant.info/v1/query?q=dbsnp.rsid:rs9939609"
    }
  },
  "rs7903146": {
    "rsid": "rs7903146",
    "gene": "TCF7L2",
    "geneName": "transcription factor 7 like 2",
    "vartype": "snv",
    "chrom": "10",
    "impact": null,
    "consequence": "MODIFIER impact",
    "proteinChange": null,
    "clinvar": [
      {
        "significance": "Likely risk allele",
        "condition": "Type 2 diabetes mellitus"
      }
    ],
    "freqs": [
      {
        "cohort": "1000 Genomes (global)",
        "allele": "T",
        "freq": 0.231
      },
      {
        "cohort": "gnomAD (global)",
        "allele": "T",
        "freq": 0.275
      },
      {
        "cohort": "TOPMed (US)",
        "allele": "T",
        "freq": 0.277
      },
      {
        "cohort": "Korean",
        "allele": "T",
        "freq": 0.029
      },
      {
        "cohort": "Japanese (ToMMo)",
        "allele": "T",
        "freq": 0.046
      },
      {
        "cohort": "Vietnamese",
        "allele": "T",
        "freq": 0.046
      },
      {
        "cohort": "UK (ALSPAC)",
        "allele": "T",
        "freq": 0.297
      }
    ],
    "sources": {
      "dbsnp": "https://www.ncbi.nlm.nih.gov/snp/rs7903146",
      "clinvar": "https://www.ncbi.nlm.nih.gov/clinvar/?term=rs7903146",
      "gnomad": "https://gnomad.broadinstitute.org/variant/rs7903146?dataset=gnomad_r4",
      "ensembl": "https://www.ensembl.org/Homo_sapiens/Variation/Explore?v=rs7903146",
      "myvariant": "https://myvariant.info/v1/query?q=dbsnp.rsid:rs7903146"
    }
  },
  "rs1726866": {
    "rsid": "rs1726866",
    "gene": "TAS2R38",
    "geneName": "taste 2 receptor member 38",
    "vartype": "snv",
    "chrom": "7",
    "impact": {
      "sift": "deleterious",
      "polyphen": "benign"
    },
    "consequence": "NON_SYNONYMOUS",
    "proteinChange": "p.Ala262Val",
    "clinvar": [],
    "freqs": [
      {
        "cohort": "1000 Genomes (global)",
        "allele": "A",
        "freq": 0.423
      },
      {
        "cohort": "gnomAD (global)",
        "allele": "A",
        "freq": 0.468
      },
      {
        "cohort": "TOPMed (US)",
        "allele": "A",
        "freq": 0.44
      },
      {
        "cohort": "Korean",
        "allele": "A",
        "freq": 0.408
      },
      {
        "cohort": "Japanese (ToMMo)",
        "allele": "A",
        "freq": 0.424
      },
      {
        "cohort": "Vietnamese",
        "allele": "A",
        "freq": 0.277
      },
      {
        "cohort": "UK (ALSPAC)",
        "allele": "A",
        "freq": 0.551
      }
    ],
    "sources": {
      "dbsnp": "https://www.ncbi.nlm.nih.gov/snp/rs1726866",
      "clinvar": "https://www.ncbi.nlm.nih.gov/clinvar/?term=rs1726866",
      "gnomad": "https://gnomad.broadinstitute.org/variant/rs1726866?dataset=gnomad_r4",
      "ensembl": "https://www.ensembl.org/Homo_sapiens/Variation/Explore?v=rs1726866",
      "myvariant": "https://myvariant.info/v1/query?q=dbsnp.rsid:rs1726866"
    }
  },
  "rs174547": {
    "rsid": "rs174547",
    "gene": "FADS1",
    "geneName": "fatty acid desaturase 1",
    "vartype": "snv",
    "chrom": "11",
    "impact": null,
    "consequence": "INTRONIC",
    "proteinChange": null,
    "clinvar": [],
    "freqs": [
      {
        "cohort": "1000 Genomes (global)",
        "allele": "C",
        "freq": 0.296
      },
      {
        "cohort": "gnomAD (global)",
        "allele": "C",
        "freq": 0.285
      },
      {
        "cohort": "TOPMed (US)",
        "allele": "C",
        "freq": 0.288
      },
      {
        "cohort": "Korean",
        "allele": "C",
        "freq": 0.323
      },
      {
        "cohort": "Japanese (ToMMo)",
        "allele": "C",
        "freq": 0.38
      },
      {
        "cohort": "Vietnamese",
        "allele": "C",
        "freq": 0.832
      },
      {
        "cohort": "UK (ALSPAC)",
        "allele": "C",
        "freq": 0.324
      }
    ],
    "sources": {
      "dbsnp": "https://www.ncbi.nlm.nih.gov/snp/rs174547",
      "clinvar": "https://www.ncbi.nlm.nih.gov/clinvar/?term=rs174547",
      "gnomad": "https://gnomad.broadinstitute.org/variant/rs174547?dataset=gnomad_r4",
      "ensembl": "https://www.ensembl.org/Homo_sapiens/Variation/Explore?v=rs174547",
      "myvariant": "https://myvariant.info/v1/query?q=dbsnp.rsid:rs174547"
    }
  },
  "rs1801133": {
    "rsid": "rs1801133",
    "gene": "MTHFR",
    "geneName": "methylenetetrahydrofolate reductase",
    "vartype": "snv",
    "chrom": "1",
    "impact": {
      "sift": "tolerated",
      "polyphen": "possibly damaging"
    },
    "consequence": "NON_SYNONYMOUS",
    "proteinChange": "p.Ala222Gly",
    "clinvar": [],
    "freqs": [
      {
        "cohort": "1000 Genomes (global)",
        "allele": "A",
        "freq": 0.246
      },
      {
        "cohort": "gnomAD (global)",
        "allele": "A",
        "freq": 0.274
      },
      {
        "cohort": "TOPMed (US)",
        "allele": "A",
        "freq": 0.291
      },
      {
        "cohort": "Korean",
        "allele": "A",
        "freq": 0.441
      },
      {
        "cohort": "Japanese (ToMMo)",
        "allele": "A",
        "freq": 0.392
      },
      {
        "cohort": "Vietnamese",
        "allele": "A",
        "freq": 0.155
      },
      {
        "cohort": "UK (ALSPAC)",
        "allele": "A",
        "freq": 0.334
      }
    ],
    "sources": {
      "dbsnp": "https://www.ncbi.nlm.nih.gov/snp/rs1801133",
      "clinvar": "https://www.ncbi.nlm.nih.gov/clinvar/?term=rs1801133",
      "gnomad": "https://gnomad.broadinstitute.org/variant/rs1801133?dataset=gnomad_r4",
      "ensembl": "https://www.ensembl.org/Homo_sapiens/Variation/Explore?v=rs1801133",
      "myvariant": "https://myvariant.info/v1/query?q=dbsnp.rsid:rs1801133"
    }
  },
  "rs10741657": {
    "rsid": "rs10741657",
    "gene": "CYP2R1",
    "geneName": "cytochrome P450 family 2 subfamily R member 1",
    "vartype": "snv",
    "chrom": "11",
    "impact": null,
    "consequence": "MODIFIER impact",
    "proteinChange": null,
    "clinvar": [],
    "freqs": [
      {
        "cohort": "1000 Genomes (global)",
        "allele": "A",
        "freq": 0.3
      },
      {
        "cohort": "gnomAD (global)",
        "allele": "A",
        "freq": 0.345
      },
      {
        "cohort": "TOPMed (US)",
        "allele": "A",
        "freq": 0.336
      },
      {
        "cohort": "Korean",
        "allele": "A",
        "freq": 0.404
      },
      {
        "cohort": "Japanese (ToMMo)",
        "allele": "A",
        "freq": 0.354
      },
      {
        "cohort": "Vietnamese",
        "allele": "A",
        "freq": 0.324
      },
      {
        "cohort": "UK (ALSPAC)",
        "allele": "A",
        "freq": 0.396
      }
    ],
    "sources": {
      "dbsnp": "https://www.ncbi.nlm.nih.gov/snp/rs10741657",
      "clinvar": "https://www.ncbi.nlm.nih.gov/clinvar/?term=rs10741657",
      "gnomad": "https://gnomad.broadinstitute.org/variant/rs10741657?dataset=gnomad_r4",
      "ensembl": "https://www.ensembl.org/Homo_sapiens/Variation/Explore?v=rs10741657",
      "myvariant": "https://myvariant.info/v1/query?q=dbsnp.rsid:rs10741657"
    }
  },
  "rs2282679": {
    "rsid": "rs2282679",
    "gene": "GC",
    "geneName": "GC vitamin D binding protein",
    "vartype": "snv",
    "chrom": "4",
    "impact": null,
    "consequence": "INTRONIC",
    "proteinChange": null,
    "clinvar": [],
    "freqs": [
      {
        "cohort": "1000 Genomes (global)",
        "allele": "G",
        "freq": 0.198
      },
      {
        "cohort": "gnomAD (global)",
        "allele": "G",
        "freq": 0.213
      },
      {
        "cohort": "TOPMed (US)",
        "allele": "G",
        "freq": 0.213
      },
      {
        "cohort": "Korean",
        "allele": "G",
        "freq": 0.284
      },
      {
        "cohort": "Japanese (ToMMo)",
        "allele": "G",
        "freq": 0.27
      },
      {
        "cohort": "Vietnamese",
        "allele": "G",
        "freq": 0.21
      },
      {
        "cohort": "UK (ALSPAC)",
        "allele": "G",
        "freq": 0.286
      }
    ],
    "sources": {
      "dbsnp": "https://www.ncbi.nlm.nih.gov/snp/rs2282679",
      "clinvar": "https://www.ncbi.nlm.nih.gov/clinvar/?term=rs2282679",
      "gnomad": "https://gnomad.broadinstitute.org/variant/rs2282679?dataset=gnomad_r4",
      "ensembl": "https://www.ensembl.org/Homo_sapiens/Variation/Explore?v=rs2282679",
      "myvariant": "https://myvariant.info/v1/query?q=dbsnp.rsid:rs2282679"
    }
  },
  "rs1799945": {
    "rsid": "rs1799945",
    "gene": "HFE",
    "geneName": "homeostatic iron regulator",
    "vartype": "snv",
    "chrom": "6",
    "impact": {
      "sift": "deleterious",
      "polyphen": "benign"
    },
    "consequence": "NON_SYNONYMOUS",
    "proteinChange": "p.His63Asp",
    "clinvar": [
      {
        "significance": "Conflicting interpretations of pathogenicity",
        "condition": "Hemochromatosis type 1 (HFE1)"
      },
      {
        "significance": "Pathogenic, low penetrance",
        "condition": "Hereditary hemochromatosis (HFE)"
      },
      {
        "significance": "no classifications from unflagged records",
        "condition": "not specified"
      },
      {
        "significance": "risk factor",
        "condition": "Cystic fibrosis (CF)"
      },
      {
        "significance": "Pathogenic",
        "condition": "Cardiomyopathy (CMYO)"
      },
      {
        "significance": "Pathogenic",
        "condition": "Variegate porphyria (VP)"
      }
    ],
    "freqs": [
      {
        "cohort": "1000 Genomes (global)",
        "allele": "G",
        "freq": 0.074
      },
      {
        "cohort": "gnomAD (global)",
        "allele": "G",
        "freq": 0.102
      },
      {
        "cohort": "TOPMed (US)",
        "allele": "G",
        "freq": 0.1
      },
      {
        "cohort": "Korean",
        "allele": "G",
        "freq": 0.049
      },
      {
        "cohort": "Japanese (ToMMo)",
        "allele": "G",
        "freq": 0.031
      },
      {
        "cohort": "Vietnamese",
        "allele": "G",
        "freq": 0.033
      },
      {
        "cohort": "UK (ALSPAC)",
        "allele": "G",
        "freq": 0.136
      }
    ],
    "sources": {
      "dbsnp": "https://www.ncbi.nlm.nih.gov/snp/rs1799945",
      "clinvar": "https://www.ncbi.nlm.nih.gov/clinvar/?term=rs1799945",
      "gnomad": "https://gnomad.broadinstitute.org/variant/rs1799945?dataset=gnomad_r4",
      "ensembl": "https://www.ensembl.org/Homo_sapiens/Variation/Explore?v=rs1799945",
      "myvariant": "https://myvariant.info/v1/query?q=dbsnp.rsid:rs1799945"
    }
  },
  "rs4680": {
    "rsid": "rs4680",
    "gene": "COMT",
    "geneName": "catechol-O-methyltransferase",
    "vartype": "snv",
    "chrom": "22",
    "impact": {
      "sift": "tolerated",
      "polyphen": "benign"
    },
    "consequence": "NON_SYNONYMOUS",
    "proteinChange": null,
    "clinvar": [
      {
        "significance": "Benign",
        "condition": "CATECHOL-O-METHYLTRANSFERASE POLYMORPHISM"
      },
      {
        "significance": "Benign",
        "condition": "not specified"
      },
      {
        "significance": "drug response",
        "condition": "Tramadol response"
      },
      {
        "significance": "Benign",
        "condition": "Schizophrenia (SCZD)"
      },
      {
        "significance": "Benign",
        "condition": "not provided"
      }
    ],
    "freqs": [
      {
        "cohort": "1000 Genomes (global)",
        "allele": "A",
        "freq": 0.37
      },
      {
        "cohort": "gnomAD (global)",
        "allele": "A",
        "freq": 0.44
      },
      {
        "cohort": "TOPMed (US)",
        "allele": "A",
        "freq": 0.42
      },
      {
        "cohort": "Korean",
        "allele": "A",
        "freq": 0.285
      },
      {
        "cohort": "Japanese (ToMMo)",
        "allele": "A",
        "freq": 0.32
      },
      {
        "cohort": "Vietnamese",
        "allele": "A",
        "freq": 0.254
      },
      {
        "cohort": "UK (ALSPAC)",
        "allele": "A",
        "freq": 0.512
      }
    ],
    "sources": {
      "dbsnp": "https://www.ncbi.nlm.nih.gov/snp/rs4680",
      "clinvar": "https://www.ncbi.nlm.nih.gov/clinvar/?term=rs4680",
      "gnomad": "https://gnomad.broadinstitute.org/variant/rs4680?dataset=gnomad_r4",
      "ensembl": "https://www.ensembl.org/Homo_sapiens/Variation/Explore?v=rs4680",
      "myvariant": "https://myvariant.info/v1/query?q=dbsnp.rsid:rs4680"
    }
  },
  "rs17822931": {
    "rsid": "rs17822931",
    "gene": "ABCC11",
    "geneName": "ATP binding cassette subfamily C member 11",
    "vartype": "snv",
    "chrom": "16",
    "impact": {
      "sift": "deleterious",
      "polyphen": "probably damaging"
    },
    "consequence": "NON_SYNONYMOUS",
    "proteinChange": "p.Gly180Arg",
    "clinvar": [
      {
        "significance": "Benign",
        "condition": "APOCRINE GLAND SECRETION, VARIATION IN"
      },
      {
        "significance": "Benign",
        "condition": "Axillary odor"
      },
      {
        "significance": "Benign",
        "condition": "Colostrum secretion"
      },
      {
        "significance": "Benign",
        "condition": "not provided"
      }
    ],
    "freqs": [
      {
        "cohort": "1000 Genomes (global)",
        "allele": "T",
        "freq": 0.284
      },
      {
        "cohort": "gnomAD (global)",
        "allele": "T",
        "freq": 0.123
      },
      {
        "cohort": "TOPMed (US)",
        "allele": "T",
        "freq": 0.13
      },
      {
        "cohort": "Korean",
        "allele": "T",
        "freq": 0.988
      },
      {
        "cohort": "Japanese (ToMMo)",
        "allele": "T",
        "freq": 0.872
      },
      {
        "cohort": "Vietnamese",
        "allele": "T",
        "freq": 0.681
      },
      {
        "cohort": "UK (ALSPAC)",
        "allele": "T",
        "freq": 0.131
      }
    ],
    "sources": {
      "dbsnp": "https://www.ncbi.nlm.nih.gov/snp/rs17822931",
      "clinvar": "https://www.ncbi.nlm.nih.gov/clinvar/?term=rs17822931",
      "gnomad": "https://gnomad.broadinstitute.org/variant/rs17822931?dataset=gnomad_r4",
      "ensembl": "https://www.ensembl.org/Homo_sapiens/Variation/Explore?v=rs17822931",
      "myvariant": "https://myvariant.info/v1/query?q=dbsnp.rsid:rs17822931"
    }
  },
  "rs12913832": {
    "rsid": "rs12913832",
    "gene": "HERC2",
    "geneName": "HECT and RLD domain containing E3 ubiquitin protein ligase 2",
    "vartype": "snv",
    "chrom": "15",
    "impact": null,
    "consequence": "INTRONIC",
    "proteinChange": null,
    "clinvar": [
      {
        "significance": "association",
        "condition": "SKIN/HAIR/EYE PIGMENTATION 1, BLUE/NONBLUE EYES (SHEP1)"
      }
    ],
    "freqs": [
      {
        "cohort": "1000 Genomes (global)",
        "allele": "G",
        "freq": 0.179
      },
      {
        "cohort": "gnomAD (global)",
        "allele": "G",
        "freq": 0.506
      },
      {
        "cohort": "TOPMed (US)",
        "allele": "G",
        "freq": 0.423
      },
      {
        "cohort": "Korean",
        "allele": "G",
        "freq": 0.001
      },
      {
        "cohort": "Japanese (ToMMo)",
        "allele": "G",
        "freq": 0
      },
      {
        "cohort": "UK (ALSPAC)",
        "allele": "G",
        "freq": 0.77
      }
    ],
    "sources": {
      "dbsnp": "https://www.ncbi.nlm.nih.gov/snp/rs12913832",
      "clinvar": "https://www.ncbi.nlm.nih.gov/clinvar/?term=rs12913832",
      "gnomad": "https://gnomad.broadinstitute.org/variant/rs12913832?dataset=gnomad_r4",
      "ensembl": "https://www.ensembl.org/Homo_sapiens/Variation/Explore?v=rs12913832",
      "myvariant": "https://myvariant.info/v1/query?q=dbsnp.rsid:rs12913832"
    }
  },
  "rs1393350": {
    "rsid": "rs1393350",
    "gene": "TYR",
    "geneName": "tyrosinase",
    "vartype": "snv",
    "chrom": "11",
    "impact": null,
    "consequence": "INTRONIC",
    "proteinChange": null,
    "clinvar": [],
    "freqs": [
      {
        "cohort": "1000 Genomes (global)",
        "allele": "A",
        "freq": 0.079
      },
      {
        "cohort": "gnomAD (global)",
        "allele": "A",
        "freq": 0.173
      },
      {
        "cohort": "TOPMed (US)",
        "allele": "A",
        "freq": 0.164
      },
      {
        "cohort": "Korean",
        "allele": "A",
        "freq": 0.001
      },
      {
        "cohort": "Japanese (ToMMo)",
        "allele": "A",
        "freq": 0
      },
      {
        "cohort": "Vietnamese",
        "allele": "A",
        "freq": 0.009
      },
      {
        "cohort": "UK (ALSPAC)",
        "allele": "A",
        "freq": 0.275
      }
    ],
    "sources": {
      "dbsnp": "https://www.ncbi.nlm.nih.gov/snp/rs1393350",
      "clinvar": "https://www.ncbi.nlm.nih.gov/clinvar/?term=rs1393350",
      "gnomad": "https://gnomad.broadinstitute.org/variant/rs1393350?dataset=gnomad_r4",
      "ensembl": "https://www.ensembl.org/Homo_sapiens/Variation/Explore?v=rs1393350",
      "myvariant": "https://myvariant.info/v1/query?q=dbsnp.rsid:rs1393350"
    }
  },
  "rs12203592": {
    "rsid": "rs12203592",
    "gene": "IRF4",
    "geneName": "interferon regulatory factor 4",
    "vartype": "snv",
    "chrom": "6",
    "impact": null,
    "consequence": "REGULATORY",
    "proteinChange": null,
    "clinvar": [
      {
        "significance": "Affects",
        "condition": "Skin/hair/eye pigmentation, variation in, 8 (SHEP8)"
      }
    ],
    "freqs": [
      {
        "cohort": "1000 Genomes (global)",
        "allele": "T",
        "freq": 0.038
      },
      {
        "cohort": "TOPMed (US)",
        "allele": "T",
        "freq": 0.105
      },
      {
        "cohort": "Japanese (ToMMo)",
        "allele": "T",
        "freq": 0
      },
      {
        "cohort": "UK (ALSPAC)",
        "allele": "T",
        "freq": 0.184
      }
    ],
    "sources": {
      "dbsnp": "https://www.ncbi.nlm.nih.gov/snp/rs12203592",
      "clinvar": "https://www.ncbi.nlm.nih.gov/clinvar/?term=rs12203592",
      "gnomad": "https://gnomad.broadinstitute.org/variant/rs12203592?dataset=gnomad_r4",
      "ensembl": "https://www.ensembl.org/Homo_sapiens/Variation/Explore?v=rs12203592",
      "myvariant": "https://myvariant.info/v1/query?q=dbsnp.rsid:rs12203592"
    }
  },
  "rs8192678": {
    "rsid": "rs8192678",
    "gene": "PPARGC1A",
    "geneName": "PPARG coactivator 1 alpha",
    "vartype": "snv",
    "chrom": "4",
    "impact": {
      "sift": "tolerated",
      "polyphen": "benign"
    },
    "consequence": "NON_SYNONYMOUS",
    "proteinChange": "p.Gly482Ser",
    "clinvar": [
      {
        "significance": "Benign",
        "condition": "PPARGC1A-related disorder"
      }
    ],
    "freqs": [
      {
        "cohort": "1000 Genomes (global)",
        "allele": "T",
        "freq": 0.257
      },
      {
        "cohort": "gnomAD (global)",
        "allele": "T",
        "freq": 0.258
      },
      {
        "cohort": "TOPMed (US)",
        "allele": "T",
        "freq": 0.26
      },
      {
        "cohort": "Korean",
        "allele": "T",
        "freq": 0.428
      },
      {
        "cohort": "Japanese (ToMMo)",
        "allele": "T",
        "freq": 0.474
      },
      {
        "cohort": "Vietnamese",
        "allele": "T",
        "freq": 0.462
      },
      {
        "cohort": "UK (ALSPAC)",
        "allele": "T",
        "freq": 0.351
      }
    ],
    "sources": {
      "dbsnp": "https://www.ncbi.nlm.nih.gov/snp/rs8192678",
      "clinvar": "https://www.ncbi.nlm.nih.gov/clinvar/?term=rs8192678",
      "gnomad": "https://gnomad.broadinstitute.org/variant/rs8192678?dataset=gnomad_r4",
      "ensembl": "https://www.ensembl.org/Homo_sapiens/Variation/Explore?v=rs8192678",
      "myvariant": "https://myvariant.info/v1/query?q=dbsnp.rsid:rs8192678"
    }
  },
  "rs6265": {
    "rsid": "rs6265",
    "gene": "BDNF",
    "geneName": "brain derived neurotrophic factor",
    "vartype": "snv",
    "chrom": "11",
    "impact": {
      "sift": "deleterious",
      "polyphen": "probably damaging"
    },
    "consequence": "NON_SYNONYMOUS",
    "proteinChange": "p.Val148Met",
    "clinvar": [
      {
        "significance": "Benign",
        "condition": "not specified"
      },
      {
        "significance": "Benign",
        "condition": "not provided"
      },
      {
        "significance": "Likely risk allele",
        "condition": "Post-traumatic stress disorder (PTSD)"
      }
    ],
    "freqs": [
      {
        "cohort": "1000 Genomes (global)",
        "allele": "T",
        "freq": 0.196
      },
      {
        "cohort": "gnomAD (global)",
        "allele": "T",
        "freq": 0.145
      },
      {
        "cohort": "TOPMed (US)",
        "allele": "T",
        "freq": 0.151
      },
      {
        "cohort": "Korean",
        "allele": "T",
        "freq": 0.448
      },
      {
        "cohort": "Japanese (ToMMo)",
        "allele": "T",
        "freq": 0.409
      },
      {
        "cohort": "Vietnamese",
        "allele": "T",
        "freq": 0.51
      },
      {
        "cohort": "UK (ALSPAC)",
        "allele": "T",
        "freq": 0.18
      }
    ],
    "sources": {
      "dbsnp": "https://www.ncbi.nlm.nih.gov/snp/rs6265",
      "clinvar": "https://www.ncbi.nlm.nih.gov/clinvar/?term=rs6265",
      "gnomad": "https://gnomad.broadinstitute.org/variant/rs6265?dataset=gnomad_r4",
      "ensembl": "https://www.ensembl.org/Homo_sapiens/Variation/Explore?v=rs6265",
      "myvariant": "https://myvariant.info/v1/query?q=dbsnp.rsid:rs6265"
    }
  },
  "rs7412": {
    "rsid": "rs7412",
    "gene": "APOE",
    "geneName": "apolipoprotein E",
    "vartype": "snv",
    "chrom": "19",
    "impact": {
      "sift": "deleterious",
      "polyphen": "probably damaging"
    },
    "consequence": "NON_SYNONYMOUS",
    "proteinChange": "p.Arg202Cys",
    "clinvar": [
      {
        "significance": "Pathogenic",
        "condition": "Familial type 3 hyperlipoproteinemia"
      },
      {
        "significance": "Pathogenic",
        "condition": "Hyperlipoproteinemia due to APOE1"
      },
      {
        "significance": "no classifications from unflagged records",
        "condition": "Familial type 3 hyperlipoproteinemia"
      },
      {
        "significance": "drug response",
        "condition": "atorvastatin response - Efficacy"
      },
      {
        "significance": "drug response",
        "condition": "Warfarin response"
      },
      {
        "significance": "Benign",
        "condition": "Hypercholesterolemia"
      }
    ],
    "freqs": [
      {
        "cohort": "1000 Genomes (global)",
        "allele": "T",
        "freq": 0.077
      },
      {
        "cohort": "gnomAD (global)",
        "allele": "T",
        "freq": 0.08
      },
      {
        "cohort": "TOPMed (US)",
        "allele": "T",
        "freq": 0.078
      },
      {
        "cohort": "Korean",
        "allele": "T",
        "freq": 0.069
      },
      {
        "cohort": "Japanese (ToMMo)",
        "allele": "T",
        "freq": 0.043
      },
      {
        "cohort": "UK (ALSPAC)",
        "allele": "T",
        "freq": 0.092
      }
    ],
    "sources": {
      "dbsnp": "https://www.ncbi.nlm.nih.gov/snp/rs7412",
      "clinvar": "https://www.ncbi.nlm.nih.gov/clinvar/?term=rs7412",
      "gnomad": "https://gnomad.broadinstitute.org/variant/rs7412?dataset=gnomad_r4",
      "ensembl": "https://www.ensembl.org/Homo_sapiens/Variation/Explore?v=rs7412",
      "myvariant": "https://myvariant.info/v1/query?q=dbsnp.rsid:rs7412"
    }
  },
  "rs662799": {
    "rsid": "rs662799",
    "gene": "ZPR1",
    "geneName": "apolipoprotein A5",
    "vartype": "snv",
    "chrom": "11",
    "impact": null,
    "consequence": "UPSTREAM",
    "proteinChange": null,
    "clinvar": [],
    "freqs": [
      {
        "cohort": "1000 Genomes (global)",
        "allele": "G",
        "freq": 0.158
      },
      {
        "cohort": "gnomAD (global)",
        "allele": "G",
        "freq": 0.096
      },
      {
        "cohort": "TOPMed (US)",
        "allele": "G",
        "freq": 0.106
      },
      {
        "cohort": "Korean",
        "allele": "G",
        "freq": 0.28
      },
      {
        "cohort": "Japanese (ToMMo)",
        "allele": "G",
        "freq": 0.351
      },
      {
        "cohort": "Vietnamese",
        "allele": "G",
        "freq": 0.307
      },
      {
        "cohort": "UK (ALSPAC)",
        "allele": "G",
        "freq": 0.062
      }
    ],
    "sources": {
      "dbsnp": "https://www.ncbi.nlm.nih.gov/snp/rs662799",
      "clinvar": "https://www.ncbi.nlm.nih.gov/clinvar/?term=rs662799",
      "gnomad": "https://gnomad.broadinstitute.org/variant/rs662799?dataset=gnomad_r4",
      "ensembl": "https://www.ensembl.org/Homo_sapiens/Variation/Explore?v=rs662799",
      "myvariant": "https://myvariant.info/v1/query?q=dbsnp.rsid:rs662799"
    }
  },
  "rs1801282": {
    "rsid": "rs1801282",
    "gene": "PPARG",
    "geneName": "peroxisome proliferator activated receptor gamma",
    "vartype": "snv",
    "chrom": "3",
    "impact": {
      "sift": "tolerated",
      "polyphen": "benign"
    },
    "consequence": "NON_SYNONYMOUS",
    "proteinChange": "p.Pro12Ser",
    "clinvar": [],
    "freqs": [
      {
        "cohort": "1000 Genomes (global)",
        "allele": "G",
        "freq": 0.069
      },
      {
        "cohort": "gnomAD (global)",
        "allele": "G",
        "freq": 0.088
      },
      {
        "cohort": "TOPMed (US)",
        "allele": "G",
        "freq": 0.08
      },
      {
        "cohort": "Korean",
        "allele": "G",
        "freq": 0.052
      },
      {
        "cohort": "Japanese (ToMMo)",
        "allele": "G",
        "freq": 0.03
      },
      {
        "cohort": "Vietnamese",
        "allele": "G",
        "freq": 0.026
      },
      {
        "cohort": "UK (ALSPAC)",
        "allele": "G",
        "freq": 0.119
      }
    ],
    "sources": {
      "dbsnp": "https://www.ncbi.nlm.nih.gov/snp/rs1801282",
      "clinvar": "https://www.ncbi.nlm.nih.gov/clinvar/?term=rs1801282",
      "gnomad": "https://gnomad.broadinstitute.org/variant/rs1801282?dataset=gnomad_r4",
      "ensembl": "https://www.ensembl.org/Homo_sapiens/Variation/Explore?v=rs1801282",
      "myvariant": "https://myvariant.info/v1/query?q=dbsnp.rsid:rs1801282"
    }
  },
  "rs6025": {
    "rsid": "rs6025",
    "gene": "F5",
    "geneName": "coagulation factor V",
    "vartype": "snv",
    "chrom": "1",
    "impact": null,
    "consequence": "NON_SYNONYMOUS",
    "proteinChange": "p.Gln534Leu",
    "clinvar": [],
    "freqs": [
      {
        "cohort": "1000 Genomes (global)",
        "allele": "T",
        "freq": 0.006
      },
      {
        "cohort": "gnomAD (global)",
        "allele": "T",
        "freq": 0.018
      },
      {
        "cohort": "TOPMed (US)",
        "allele": "T",
        "freq": 0.017
      },
      {
        "cohort": "Korean",
        "allele": "C",
        "freq": 0
      }
    ],
    "sources": {
      "dbsnp": "https://www.ncbi.nlm.nih.gov/snp/rs6025",
      "clinvar": "https://www.ncbi.nlm.nih.gov/clinvar/?term=rs6025",
      "gnomad": "https://gnomad.broadinstitute.org/variant/rs6025?dataset=gnomad_r4",
      "ensembl": "https://www.ensembl.org/Homo_sapiens/Variation/Explore?v=rs6025",
      "myvariant": "https://myvariant.info/v1/query?q=dbsnp.rsid:rs6025"
    }
  },
  "rs4253778": {
    "rsid": "rs4253778",
    "gene": "PPARA",
    "geneName": "peroxisome proliferator activated receptor alpha",
    "vartype": "snv",
    "chrom": "22",
    "impact": null,
    "consequence": "MODIFIER impact",
    "proteinChange": null,
    "clinvar": [],
    "freqs": [
      {
        "cohort": "1000 Genomes (global)",
        "allele": "C",
        "freq": 0.287
      },
      {
        "cohort": "TOPMed (US)",
        "allele": "C",
        "freq": 0.331
      },
      {
        "cohort": "Japanese (ToMMo)",
        "allele": "C",
        "freq": 0
      },
      {
        "cohort": "UK (ALSPAC)",
        "allele": "C",
        "freq": 0.185
      }
    ],
    "sources": {
      "dbsnp": "https://www.ncbi.nlm.nih.gov/snp/rs4253778",
      "clinvar": "https://www.ncbi.nlm.nih.gov/clinvar/?term=rs4253778",
      "gnomad": "https://gnomad.broadinstitute.org/variant/rs4253778?dataset=gnomad_r4",
      "ensembl": "https://www.ensembl.org/Homo_sapiens/Variation/Explore?v=rs4253778",
      "myvariant": "https://myvariant.info/v1/query?q=dbsnp.rsid:rs4253778"
    }
  },
  "rs1042713": {
    "rsid": "rs1042713",
    "gene": "ADRB2",
    "geneName": "adrenoceptor beta 2",
    "vartype": "snv",
    "chrom": "5",
    "impact": {
      "sift": "tolerated",
      "polyphen": "benign"
    },
    "consequence": "NON_SYNONYMOUS",
    "proteinChange": "p.Gly16Arg",
    "clinvar": [],
    "freqs": [
      {
        "cohort": "1000 Genomes (global)",
        "allele": "A",
        "freq": 0.476
      },
      {
        "cohort": "gnomAD (global)",
        "allele": "A",
        "freq": 0.425
      },
      {
        "cohort": "TOPMed (US)",
        "allele": "A",
        "freq": 0.427
      },
      {
        "cohort": "Korean",
        "allele": "A",
        "freq": 0.538
      },
      {
        "cohort": "Japanese (ToMMo)",
        "allele": "A",
        "freq": 0.497
      },
      {
        "cohort": "Vietnamese",
        "allele": "A",
        "freq": 0.559
      },
      {
        "cohort": "UK (ALSPAC)",
        "allele": "A",
        "freq": 0.375
      }
    ],
    "sources": {
      "dbsnp": "https://www.ncbi.nlm.nih.gov/snp/rs1042713",
      "clinvar": "https://www.ncbi.nlm.nih.gov/clinvar/?term=rs1042713",
      "gnomad": "https://gnomad.broadinstitute.org/variant/rs1042713?dataset=gnomad_r4",
      "ensembl": "https://www.ensembl.org/Homo_sapiens/Variation/Explore?v=rs1042713",
      "myvariant": "https://myvariant.info/v1/query?q=dbsnp.rsid:rs1042713"
    }
  },
  "rs1800012": {
    "rsid": "rs1800012",
    "gene": "COL1A1",
    "geneName": "collagen type I alpha 1 chain",
    "vartype": "snv",
    "chrom": "17",
    "impact": null,
    "consequence": "REGULATORY",
    "proteinChange": null,
    "clinvar": [
      {
        "significance": "Benign",
        "condition": "not specified"
      },
      {
        "significance": "Benign",
        "condition": "Osteogenesis imperfecta type I (OI1)"
      },
      {
        "significance": "Benign",
        "condition": "not provided"
      }
    ],
    "freqs": [
      {
        "cohort": "1000 Genomes (global)",
        "allele": "A",
        "freq": 0.094
      },
      {
        "cohort": "gnomAD (global)",
        "allele": "A",
        "freq": 0.139
      },
      {
        "cohort": "TOPMed (US)",
        "allele": "A",
        "freq": 0.134
      },
      {
        "cohort": "Korean",
        "allele": "A",
        "freq": 0
      },
      {
        "cohort": "UK (ALSPAC)",
        "allele": "A",
        "freq": 0.19
      }
    ],
    "sources": {
      "dbsnp": "https://www.ncbi.nlm.nih.gov/snp/rs1800012",
      "clinvar": "https://www.ncbi.nlm.nih.gov/clinvar/?term=rs1800012",
      "gnomad": "https://gnomad.broadinstitute.org/variant/rs1800012?dataset=gnomad_r4",
      "ensembl": "https://www.ensembl.org/Homo_sapiens/Variation/Explore?v=rs1800012",
      "myvariant": "https://myvariant.info/v1/query?q=dbsnp.rsid:rs1800012"
    }
  },
  "rs1049434": {
    "rsid": "rs1049434",
    "gene": "SLC16A1",
    "geneName": "solute carrier family 16 member 1",
    "vartype": "snv",
    "chrom": "1",
    "impact": null,
    "consequence": "SYNONYMOUS",
    "proteinChange": "p.Asp490Asp",
    "clinvar": [],
    "freqs": [
      {
        "cohort": "1000 Genomes (global)",
        "allele": "A",
        "freq": 0.32
      },
      {
        "cohort": "gnomAD (global)",
        "allele": "A",
        "freq": 0.339
      },
      {
        "cohort": "TOPMed (US)",
        "allele": "A",
        "freq": 0.338
      },
      {
        "cohort": "Korean",
        "allele": "A",
        "freq": 0.346
      },
      {
        "cohort": "Japanese (ToMMo)",
        "allele": "A",
        "freq": 0.34
      },
      {
        "cohort": "Vietnamese",
        "allele": "A",
        "freq": 0.331
      },
      {
        "cohort": "UK (ALSPAC)",
        "allele": "A",
        "freq": 0.432
      }
    ],
    "sources": {
      "dbsnp": "https://www.ncbi.nlm.nih.gov/snp/rs1049434",
      "clinvar": "https://www.ncbi.nlm.nih.gov/clinvar/?term=rs1049434",
      "gnomad": "https://gnomad.broadinstitute.org/variant/rs1049434?dataset=gnomad_r4",
      "ensembl": "https://www.ensembl.org/Homo_sapiens/Variation/Explore?v=rs1049434",
      "myvariant": "https://myvariant.info/v1/query?q=dbsnp.rsid:rs1049434"
    }
  },
  "rs699": {
    "rsid": "rs699",
    "gene": "AGT",
    "geneName": "angiotensinogen",
    "vartype": "snv",
    "chrom": "1",
    "impact": {
      "sift": "tolerated",
      "polyphen": "benign"
    },
    "consequence": "NON_SYNONYMOUS",
    "proteinChange": "p.Met268Thr",
    "clinvar": [
      {
        "significance": "Benign",
        "condition": "Hypertension, essential, susceptibility to"
      },
      {
        "significance": "Benign",
        "condition": "not specified"
      },
      {
        "significance": "Benign",
        "condition": "Renal tubular dysgenesis"
      },
      {
        "significance": "Benign",
        "condition": "not provided"
      },
      {
        "significance": "Benign",
        "condition": "Hypertensive disorder"
      }
    ],
    "freqs": [
      {
        "cohort": "1000 Genomes (global)",
        "allele": "A",
        "freq": 0.294
      },
      {
        "cohort": "gnomAD (global)",
        "allele": "A",
        "freq": 0.423
      },
      {
        "cohort": "TOPMed (US)",
        "allele": "A",
        "freq": 0.396
      },
      {
        "cohort": "Korean",
        "allele": "A",
        "freq": 0.197
      },
      {
        "cohort": "Japanese (ToMMo)",
        "allele": "A",
        "freq": 0.182
      },
      {
        "cohort": "Vietnamese",
        "allele": "A",
        "freq": 0.106
      },
      {
        "cohort": "UK (ALSPAC)",
        "allele": "A",
        "freq": 0.605
      }
    ],
    "sources": {
      "dbsnp": "https://www.ncbi.nlm.nih.gov/snp/rs699",
      "clinvar": "https://www.ncbi.nlm.nih.gov/clinvar/?term=rs699",
      "gnomad": "https://gnomad.broadinstitute.org/variant/rs699?dataset=gnomad_r4",
      "ensembl": "https://www.ensembl.org/Homo_sapiens/Variation/Explore?v=rs699",
      "myvariant": "https://myvariant.info/v1/query?q=dbsnp.rsid:rs699"
    }
  },
  "rs4880": {
    "rsid": "rs4880",
    "gene": "SOD2",
    "geneName": "superoxide dismutase 2",
    "vartype": "snv",
    "chrom": "6",
    "impact": {
      "sift": "tolerated",
      "polyphen": "benign"
    },
    "consequence": "NON_SYNONYMOUS",
    "proteinChange": "p.Val16Ala",
    "clinvar": [
      {
        "significance": "Benign",
        "condition": "SOD2 POLYMORPHISM"
      },
      {
        "significance": "Likely risk allele; risk factor",
        "condition": "Microvascular complications of diabetes, susceptibility to, 6"
      }
    ],
    "freqs": [
      {
        "cohort": "1000 Genomes (global)",
        "allele": "G",
        "freq": 0.414
      },
      {
        "cohort": "gnomAD (global)",
        "allele": "G",
        "freq": 0.472
      },
      {
        "cohort": "TOPMed (US)",
        "allele": "G",
        "freq": 0.472
      },
      {
        "cohort": "Korean",
        "allele": "G",
        "freq": 0.12
      },
      {
        "cohort": "Japanese (ToMMo)",
        "allele": "G",
        "freq": 0.122
      },
      {
        "cohort": "Vietnamese",
        "allele": "G",
        "freq": 0.145
      },
      {
        "cohort": "UK (ALSPAC)",
        "allele": "G",
        "freq": 0.477
      }
    ],
    "sources": {
      "dbsnp": "https://www.ncbi.nlm.nih.gov/snp/rs4880",
      "clinvar": "https://www.ncbi.nlm.nih.gov/clinvar/?term=rs4880",
      "gnomad": "https://gnomad.broadinstitute.org/variant/rs4880?dataset=gnomad_r4",
      "ensembl": "https://www.ensembl.org/Homo_sapiens/Variation/Explore?v=rs4880",
      "myvariant": "https://myvariant.info/v1/query?q=dbsnp.rsid:rs4880"
    }
  },
  "rs1001179": {
    "rsid": "rs1001179",
    "gene": "CAT",
    "geneName": "catalase",
    "vartype": "snv",
    "chrom": "11",
    "impact": null,
    "consequence": "MODIFIER impact",
    "proteinChange": null,
    "clinvar": [],
    "freqs": [
      {
        "cohort": "1000 Genomes (global)",
        "allele": "T",
        "freq": 0.125
      },
      {
        "cohort": "gnomAD (global)",
        "allele": "T",
        "freq": 0.16
      },
      {
        "cohort": "TOPMed (US)",
        "allele": "T",
        "freq": 0.145
      },
      {
        "cohort": "Korean",
        "allele": "T",
        "freq": 0.03
      },
      {
        "cohort": "Japanese (ToMMo)",
        "allele": "T",
        "freq": 0.025
      },
      {
        "cohort": "Vietnamese",
        "allele": "T",
        "freq": 0.023
      },
      {
        "cohort": "UK (ALSPAC)",
        "allele": "T",
        "freq": 0.223
      }
    ],
    "sources": {
      "dbsnp": "https://www.ncbi.nlm.nih.gov/snp/rs1001179",
      "clinvar": "https://www.ncbi.nlm.nih.gov/clinvar/?term=rs1001179",
      "gnomad": "https://gnomad.broadinstitute.org/variant/rs1001179?dataset=gnomad_r4",
      "ensembl": "https://www.ensembl.org/Homo_sapiens/Variation/Explore?v=rs1001179",
      "myvariant": "https://myvariant.info/v1/query?q=dbsnp.rsid:rs1001179"
    }
  },
  "rs1695": {
    "rsid": "rs1695",
    "gene": "GSTP1",
    "geneName": "glutathione S-transferase pi 1",
    "vartype": "snv",
    "chrom": "11",
    "impact": {
      "sift": "tolerated",
      "polyphen": "benign"
    },
    "consequence": "NON_SYNONYMOUS",
    "proteinChange": "p.Ile105Val",
    "clinvar": [
      {
        "significance": "Benign",
        "condition": "GLUTATHIONE S-TRANSFERASE PI POLYMORPHISM, TYPE B"
      },
      {
        "significance": "Benign",
        "condition": "GLUTATHIONE S-TRANSFERASE PI POLYMORPHISM, TYPE C"
      },
      {
        "significance": "Benign",
        "condition": "not provided"
      },
      {
        "significance": "Benign",
        "condition": "Abnormality of immune system physiology"
      }
    ],
    "freqs": [
      {
        "cohort": "1000 Genomes (global)",
        "allele": "G",
        "freq": 0.362
      },
      {
        "cohort": "gnomAD (global)",
        "allele": "G",
        "freq": 0.366
      },
      {
        "cohort": "TOPMed (US)",
        "allele": "G",
        "freq": 0.38
      },
      {
        "cohort": "Korean",
        "allele": "G",
        "freq": 0.183
      },
      {
        "cohort": "Japanese (ToMMo)",
        "allele": "G",
        "freq": 0.142
      },
      {
        "cohort": "Vietnamese",
        "allele": "G",
        "freq": 0.237
      },
      {
        "cohort": "UK (ALSPAC)",
        "allele": "G",
        "freq": 0.345
      }
    ],
    "sources": {
      "dbsnp": "https://www.ncbi.nlm.nih.gov/snp/rs1695",
      "clinvar": "https://www.ncbi.nlm.nih.gov/clinvar/?term=rs1695",
      "gnomad": "https://gnomad.broadinstitute.org/variant/rs1695?dataset=gnomad_r4",
      "ensembl": "https://www.ensembl.org/Homo_sapiens/Variation/Explore?v=rs1695",
      "myvariant": "https://myvariant.info/v1/query?q=dbsnp.rsid:rs1695"
    }
  },
  "rs1800440": {
    "rsid": "rs1800440",
    "gene": "CYP1B1",
    "geneName": "cytochrome P450 family 1 subfamily B member 1",
    "vartype": "snv",
    "chrom": "2",
    "impact": null,
    "consequence": "NON_SYNONYMOUS",
    "proteinChange": "p.Asn453Thr",
    "clinvar": [],
    "freqs": [
      {
        "cohort": "1000 Genomes (global)",
        "allele": "C",
        "freq": 0.098
      },
      {
        "cohort": "TOPMed (US)",
        "allele": "C",
        "freq": 0.124
      },
      {
        "cohort": "Korean",
        "allele": "C",
        "freq": 0.005
      },
      {
        "cohort": "Japanese (ToMMo)",
        "allele": "C",
        "freq": 0.001
      },
      {
        "cohort": "UK (ALSPAC)",
        "allele": "C",
        "freq": 0.177
      }
    ],
    "sources": {
      "dbsnp": "https://www.ncbi.nlm.nih.gov/snp/rs1800440",
      "clinvar": "https://www.ncbi.nlm.nih.gov/clinvar/?term=rs1800440",
      "gnomad": "https://gnomad.broadinstitute.org/variant/rs1800440?dataset=gnomad_r4",
      "ensembl": "https://www.ensembl.org/Homo_sapiens/Variation/Explore?v=rs1800440",
      "myvariant": "https://myvariant.info/v1/query?q=dbsnp.rsid:rs1800440"
    }
  },
  "rs1042522": {
    "rsid": "rs1042522",
    "gene": "TP53",
    "geneName": "tumor protein p53",
    "vartype": "snv",
    "chrom": "17",
    "impact": {
      "sift": "deleterious",
      "polyphen": "probably damaging"
    },
    "consequence": "NON_SYNONYMOUS",
    "proteinChange": "p.Pro72His",
    "clinvar": [
      {
        "significance": "Conflicting interpretations of pathogenicity",
        "condition": "Hereditary cancer-predisposing syndrome"
      },
      {
        "significance": "Benign",
        "condition": "Li-Fraumeni syndrome (LFS)"
      },
      {
        "significance": "Likely benign",
        "condition": "TP53-related disorder"
      }
    ],
    "freqs": [
      {
        "cohort": "1000 Genomes (global)",
        "allele": "G",
        "freq": 0.456
      },
      {
        "cohort": "gnomAD (global)",
        "allele": "G",
        "freq": 0.373
      },
      {
        "cohort": "TOPMed (US)",
        "allele": "G",
        "freq": 0.383
      },
      {
        "cohort": "Korean",
        "allele": "G",
        "freq": 0.345
      },
      {
        "cohort": "Japanese (ToMMo)",
        "allele": "G",
        "freq": 0.35
      },
      {
        "cohort": "Vietnamese",
        "allele": "G",
        "freq": 0.505
      },
      {
        "cohort": "UK (ALSPAC)",
        "allele": "G",
        "freq": 0.25
      }
    ],
    "sources": {
      "dbsnp": "https://www.ncbi.nlm.nih.gov/snp/rs1042522",
      "clinvar": "https://www.ncbi.nlm.nih.gov/clinvar/?term=rs1042522",
      "gnomad": "https://gnomad.broadinstitute.org/variant/rs1042522?dataset=gnomad_r4",
      "ensembl": "https://www.ensembl.org/Homo_sapiens/Variation/Explore?v=rs1042522",
      "myvariant": "https://myvariant.info/v1/query?q=dbsnp.rsid:rs1042522"
    }
  },
  "rs1421085": {
    "rsid": "rs1421085",
    "gene": "FTO",
    "geneName": "FTO alpha-ketoglutarate dependent dioxygenase",
    "vartype": "snv",
    "chrom": "16",
    "impact": null,
    "consequence": "REGULATORY",
    "proteinChange": null,
    "clinvar": [
      {
        "significance": "risk factor",
        "condition": "OBESITY (BMIQ14), SUSCEPTIBILITY TO"
      }
    ],
    "freqs": [
      {
        "cohort": "1000 Genomes (global)",
        "allele": "C",
        "freq": 0.226
      },
      {
        "cohort": "gnomAD (global)",
        "allele": "C",
        "freq": 0.306
      },
      {
        "cohort": "TOPMed (US)",
        "allele": "C",
        "freq": 0.285
      },
      {
        "cohort": "Korean",
        "allele": "C",
        "freq": 0.13
      },
      {
        "cohort": "Japanese (ToMMo)",
        "allele": "C",
        "freq": 0.197
      },
      {
        "cohort": "Vietnamese",
        "allele": "C",
        "freq": 0.15
      },
      {
        "cohort": "UK (ALSPAC)",
        "allele": "C",
        "freq": 0.397
      }
    ],
    "sources": {
      "dbsnp": "https://www.ncbi.nlm.nih.gov/snp/rs1421085",
      "clinvar": "https://www.ncbi.nlm.nih.gov/clinvar/?term=rs1421085",
      "gnomad": "https://gnomad.broadinstitute.org/variant/rs1421085?dataset=gnomad_r4",
      "ensembl": "https://www.ensembl.org/Homo_sapiens/Variation/Explore?v=rs1421085",
      "myvariant": "https://myvariant.info/v1/query?q=dbsnp.rsid:rs1421085"
    }
  },
  "rs17782313": {
    "rsid": "rs17782313",
    "gene": "PMAIP1-MC4R",
    "geneName": null,
    "vartype": "snv",
    "chrom": "18",
    "impact": null,
    "consequence": "INTERGENIC",
    "proteinChange": null,
    "clinvar": [],
    "freqs": [
      {
        "cohort": "1000 Genomes (global)",
        "allele": "C",
        "freq": 0.237
      },
      {
        "cohort": "gnomAD (global)",
        "allele": "C",
        "freq": 0.235
      },
      {
        "cohort": "TOPMed (US)",
        "allele": "C",
        "freq": 0.236
      },
      {
        "cohort": "Korean",
        "allele": "C",
        "freq": 0.237
      },
      {
        "cohort": "Japanese (ToMMo)",
        "allele": "C",
        "freq": 0.231
      },
      {
        "cohort": "Vietnamese",
        "allele": "C",
        "freq": 0.139
      },
      {
        "cohort": "UK (ALSPAC)",
        "allele": "C",
        "freq": 0.231
      }
    ],
    "sources": {
      "dbsnp": "https://www.ncbi.nlm.nih.gov/snp/rs17782313",
      "clinvar": "https://www.ncbi.nlm.nih.gov/clinvar/?term=rs17782313",
      "gnomad": "https://gnomad.broadinstitute.org/variant/rs17782313?dataset=gnomad_r4",
      "ensembl": "https://www.ensembl.org/Homo_sapiens/Variation/Explore?v=rs17782313",
      "myvariant": "https://myvariant.info/v1/query?q=dbsnp.rsid:rs17782313"
    }
  },
  "rs5082": {
    "rsid": "rs5082",
    "gene": "APOA2",
    "geneName": "apolipoprotein A2",
    "vartype": "snv",
    "chrom": "1",
    "impact": null,
    "consequence": "MODIFIER impact",
    "proteinChange": null,
    "clinvar": [],
    "freqs": [
      {
        "cohort": "1000 Genomes (global)",
        "allele": "G",
        "freq": 0.238
      },
      {
        "cohort": "gnomAD (global)",
        "allele": "G",
        "freq": 0.324
      },
      {
        "cohort": "TOPMed (US)",
        "allele": "G",
        "freq": 0.306
      },
      {
        "cohort": "Korean",
        "allele": "G",
        "freq": 0.068
      },
      {
        "cohort": "Japanese (ToMMo)",
        "allele": "G",
        "freq": 0.061
      },
      {
        "cohort": "Vietnamese",
        "allele": "G",
        "freq": 0.071
      },
      {
        "cohort": "UK (ALSPAC)",
        "allele": "G",
        "freq": 0.384
      }
    ],
    "sources": {
      "dbsnp": "https://www.ncbi.nlm.nih.gov/snp/rs5082",
      "clinvar": "https://www.ncbi.nlm.nih.gov/clinvar/?term=rs5082",
      "gnomad": "https://gnomad.broadinstitute.org/variant/rs5082?dataset=gnomad_r4",
      "ensembl": "https://www.ensembl.org/Homo_sapiens/Variation/Explore?v=rs5082",
      "myvariant": "https://myvariant.info/v1/query?q=dbsnp.rsid:rs5082"
    }
  },
  "rs2070895": {
    "rsid": "rs2070895",
    "gene": "LIPC",
    "geneName": "lipase C, hepatic type",
    "vartype": "snv",
    "chrom": "15",
    "impact": null,
    "consequence": "MODIFIER impact",
    "proteinChange": null,
    "clinvar": [],
    "freqs": [
      {
        "cohort": "1000 Genomes (global)",
        "allele": "A",
        "freq": 0.399
      },
      {
        "cohort": "gnomAD (global)",
        "allele": "A",
        "freq": 0.335
      },
      {
        "cohort": "TOPMed (US)",
        "allele": "A",
        "freq": 0.355
      },
      {
        "cohort": "Korean",
        "allele": "A",
        "freq": 0.421
      },
      {
        "cohort": "Japanese (ToMMo)",
        "allele": "A",
        "freq": 0.513
      },
      {
        "cohort": "Vietnamese",
        "allele": "A",
        "freq": 0.396
      },
      {
        "cohort": "UK (ALSPAC)",
        "allele": "A",
        "freq": 0.205
      }
    ],
    "sources": {
      "dbsnp": "https://www.ncbi.nlm.nih.gov/snp/rs2070895",
      "clinvar": "https://www.ncbi.nlm.nih.gov/clinvar/?term=rs2070895",
      "gnomad": "https://gnomad.broadinstitute.org/variant/rs2070895?dataset=gnomad_r4",
      "ensembl": "https://www.ensembl.org/Homo_sapiens/Variation/Explore?v=rs2070895",
      "myvariant": "https://myvariant.info/v1/query?q=dbsnp.rsid:rs2070895"
    }
  },
  "rs9923231": {
    "rsid": "rs9923231",
    "gene": "VKORC1",
    "geneName": "vitamin K epoxide reductase complex subunit 1",
    "vartype": "snv",
    "chrom": "16",
    "impact": null,
    "consequence": "MODIFIER impact",
    "proteinChange": null,
    "clinvar": [],
    "freqs": [
      {
        "cohort": "1000 Genomes (global)",
        "allele": "T",
        "freq": 0.344
      },
      {
        "cohort": "gnomAD (global)",
        "allele": "T",
        "freq": 0.312
      },
      {
        "cohort": "TOPMed (US)",
        "allele": "T",
        "freq": 0.323
      },
      {
        "cohort": "Korean",
        "allele": "T",
        "freq": 0.922
      },
      {
        "cohort": "Japanese (ToMMo)",
        "allele": "T",
        "freq": 0.906
      },
      {
        "cohort": "Vietnamese",
        "allele": "T",
        "freq": 0.818
      },
      {
        "cohort": "UK (ALSPAC)",
        "allele": "T",
        "freq": 0.368
      }
    ],
    "sources": {
      "dbsnp": "https://www.ncbi.nlm.nih.gov/snp/rs9923231",
      "clinvar": "https://www.ncbi.nlm.nih.gov/clinvar/?term=rs9923231",
      "gnomad": "https://gnomad.broadinstitute.org/variant/rs9923231?dataset=gnomad_r4",
      "ensembl": "https://www.ensembl.org/Homo_sapiens/Variation/Explore?v=rs9923231",
      "myvariant": "https://myvariant.info/v1/query?q=dbsnp.rsid:rs9923231"
    }
  },
  "rs4244285": {
    "rsid": "rs4244285",
    "gene": "CYP2C19",
    "geneName": "cytochrome P450 family 2 subfamily C member 19",
    "vartype": "snv",
    "chrom": "10",
    "impact": null,
    "consequence": "SYNONYMOUS",
    "proteinChange": "p.Pro227Pro",
    "clinvar": [],
    "freqs": [
      {
        "cohort": "1000 Genomes (global)",
        "allele": "A",
        "freq": 0.215
      },
      {
        "cohort": "gnomAD (global)",
        "allele": "A",
        "freq": 0.161
      },
      {
        "cohort": "TOPMed (US)",
        "allele": "A",
        "freq": 0.16
      },
      {
        "cohort": "Korean",
        "allele": "A",
        "freq": 0.276
      },
      {
        "cohort": "Japanese (ToMMo)",
        "allele": "A",
        "freq": 0.299
      },
      {
        "cohort": "Vietnamese",
        "allele": "A",
        "freq": 0.3
      },
      {
        "cohort": "UK (ALSPAC)",
        "allele": "A",
        "freq": 0.151
      }
    ],
    "sources": {
      "dbsnp": "https://www.ncbi.nlm.nih.gov/snp/rs4244285",
      "clinvar": "https://www.ncbi.nlm.nih.gov/clinvar/?term=rs4244285",
      "gnomad": "https://gnomad.broadinstitute.org/variant/rs4244285?dataset=gnomad_r4",
      "ensembl": "https://www.ensembl.org/Homo_sapiens/Variation/Explore?v=rs4244285",
      "myvariant": "https://myvariant.info/v1/query?q=dbsnp.rsid:rs4244285"
    }
  },
  "rs1801086": {
    "rsid": "rs1801086",
    "gene": "RYR1",
    "geneName": "ryanodine receptor 1",
    "vartype": "snv",
    "chrom": "19",
    "impact": {
      "sift": "deleterious",
      "polyphen": "probably damaging"
    },
    "consequence": "NON_SYNONYMOUS",
    "proteinChange": "p.Gly248Arg",
    "clinvar": [
      {
        "significance": "Pathogenic",
        "condition": "not provided"
      },
      {
        "significance": "Pathogenic",
        "condition": "RYR1-related disorder"
      },
      {
        "significance": "Pathogenic",
        "condition": "Malignant hyperthermia, susceptibility to, 1 (MHS1)"
      },
      {
        "significance": "Pathogenic",
        "condition": "Autism spectrum disorder due to AUTS2 deficiency (MRD26)"
      }
    ],
    "freqs": [
      {
        "cohort": "TOPMed (US)",
        "allele": "G",
        "freq": 1
      },
      {
        "cohort": "Japanese (ToMMo)",
        "allele": "G",
        "freq": 1
      }
    ],
    "sources": {
      "dbsnp": "https://www.ncbi.nlm.nih.gov/snp/rs1801086",
      "clinvar": "https://www.ncbi.nlm.nih.gov/clinvar/?term=rs1801086",
      "gnomad": "https://gnomad.broadinstitute.org/variant/rs1801086?dataset=gnomad_r4",
      "ensembl": "https://www.ensembl.org/Homo_sapiens/Variation/Explore?v=rs1801086",
      "myvariant": "https://myvariant.info/v1/query?q=dbsnp.rsid:rs1801086"
    }
  }
}
